// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	episode "github.com/bangumi/server/internal/episode"
	mock "github.com/stretchr/testify/mock"

	model "github.com/bangumi/server/internal/model"

	query "github.com/bangumi/server/dal/query"
)

// EpisodeRepo is an autogenerated mock type for the Repo type
type EpisodeRepo struct {
	mock.Mock
}

type EpisodeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *EpisodeRepo) EXPECT() *EpisodeRepo_Expecter {
	return &EpisodeRepo_Expecter{mock: &_m.Mock}
}

// AddNewComment provides a mock function with given fields: ctx, comment
func (_m *EpisodeRepo) AddNewComment(ctx context.Context, comment model.EpisodeComment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddNewComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EpisodeComment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EpisodeRepo_AddNewComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewComment'
type EpisodeRepo_AddNewComment_Call struct {
	*mock.Call
}

// AddNewComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment model.EpisodeComment
func (_e *EpisodeRepo_Expecter) AddNewComment(ctx interface{}, comment interface{}) *EpisodeRepo_AddNewComment_Call {
	return &EpisodeRepo_AddNewComment_Call{Call: _e.mock.On("AddNewComment", ctx, comment)}
}

func (_c *EpisodeRepo_AddNewComment_Call) Run(run func(ctx context.Context, comment model.EpisodeComment)) *EpisodeRepo_AddNewComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.EpisodeComment))
	})
	return _c
}

func (_c *EpisodeRepo_AddNewComment_Call) Return(_a0 error) *EpisodeRepo_AddNewComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EpisodeRepo_AddNewComment_Call) RunAndReturn(run func(context.Context, model.EpisodeComment) error) *EpisodeRepo_AddNewComment_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx, subjectID, filter
func (_m *EpisodeRepo) Count(ctx context.Context, subjectID uint32, filter episode.Filter) (int64, error) {
	ret := _m.Called(ctx, subjectID, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, episode.Filter) (int64, error)); ok {
		return rf(ctx, subjectID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, episode.Filter) int64); ok {
		r0 = rf(ctx, subjectID, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, episode.Filter) error); ok {
		r1 = rf(ctx, subjectID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeRepo_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type EpisodeRepo_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID uint32
//   - filter episode.Filter
func (_e *EpisodeRepo_Expecter) Count(ctx interface{}, subjectID interface{}, filter interface{}) *EpisodeRepo_Count_Call {
	return &EpisodeRepo_Count_Call{Call: _e.mock.On("Count", ctx, subjectID, filter)}
}

func (_c *EpisodeRepo_Count_Call) Run(run func(ctx context.Context, subjectID uint32, filter episode.Filter)) *EpisodeRepo_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(episode.Filter))
	})
	return _c
}

func (_c *EpisodeRepo_Count_Call) Return(_a0 int64, _a1 error) *EpisodeRepo_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EpisodeRepo_Count_Call) RunAndReturn(run func(context.Context, uint32, episode.Filter) (int64, error)) *EpisodeRepo_Count_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function with given fields: ctx, commentID
func (_m *EpisodeRepo) DeleteComment(ctx context.Context, commentID uint32) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EpisodeRepo_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type EpisodeRepo_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uint32
func (_e *EpisodeRepo_Expecter) DeleteComment(ctx interface{}, commentID interface{}) *EpisodeRepo_DeleteComment_Call {
	return &EpisodeRepo_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, commentID)}
}

func (_c *EpisodeRepo_DeleteComment_Call) Run(run func(ctx context.Context, commentID uint32)) *EpisodeRepo_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *EpisodeRepo_DeleteComment_Call) Return(_a0 error) *EpisodeRepo_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EpisodeRepo_DeleteComment_Call) RunAndReturn(run func(context.Context, uint32) error) *EpisodeRepo_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, episodeID
func (_m *EpisodeRepo) Get(ctx context.Context, episodeID uint32) (episode.Episode, error) {
	ret := _m.Called(ctx, episodeID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 episode.Episode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (episode.Episode, error)); ok {
		return rf(ctx, episodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) episode.Episode); ok {
		r0 = rf(ctx, episodeID)
	} else {
		r0 = ret.Get(0).(episode.Episode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, episodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EpisodeRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - episodeID uint32
func (_e *EpisodeRepo_Expecter) Get(ctx interface{}, episodeID interface{}) *EpisodeRepo_Get_Call {
	return &EpisodeRepo_Get_Call{Call: _e.mock.On("Get", ctx, episodeID)}
}

func (_c *EpisodeRepo_Get_Call) Run(run func(ctx context.Context, episodeID uint32)) *EpisodeRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *EpisodeRepo_Get_Call) Return(_a0 episode.Episode, _a1 error) *EpisodeRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EpisodeRepo_Get_Call) RunAndReturn(run func(context.Context, uint32) (episode.Episode, error)) *EpisodeRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllComment provides a mock function with given fields: ctx, episodeID, offset, limit
func (_m *EpisodeRepo) GetAllComment(ctx context.Context, episodeID uint32, offset int, limit int) ([]model.EpisodeComment, error) {
	ret := _m.Called(ctx, episodeID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllComment")
	}

	var r0 []model.EpisodeComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, int, int) ([]model.EpisodeComment, error)); ok {
		return rf(ctx, episodeID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, int, int) []model.EpisodeComment); ok {
		r0 = rf(ctx, episodeID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.EpisodeComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, int, int) error); ok {
		r1 = rf(ctx, episodeID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeRepo_GetAllComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllComment'
type EpisodeRepo_GetAllComment_Call struct {
	*mock.Call
}

// GetAllComment is a helper method to define mock.On call
//   - ctx context.Context
//   - episodeID uint32
//   - offset int
//   - limit int
func (_e *EpisodeRepo_Expecter) GetAllComment(ctx interface{}, episodeID interface{}, offset interface{}, limit interface{}) *EpisodeRepo_GetAllComment_Call {
	return &EpisodeRepo_GetAllComment_Call{Call: _e.mock.On("GetAllComment", ctx, episodeID, offset, limit)}
}

func (_c *EpisodeRepo_GetAllComment_Call) Run(run func(ctx context.Context, episodeID uint32, offset int, limit int)) *EpisodeRepo_GetAllComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *EpisodeRepo_GetAllComment_Call) Return(_a0 []model.EpisodeComment, _a1 error) *EpisodeRepo_GetAllComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EpisodeRepo_GetAllComment_Call) RunAndReturn(run func(context.Context, uint32, int, int) ([]model.EpisodeComment, error)) *EpisodeRepo_GetAllComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetComment provides a mock function with given fields: ctx, commentID
func (_m *EpisodeRepo) GetComment(ctx context.Context, commentID uint32) (model.EpisodeComment, error) {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetComment")
	}

	var r0 model.EpisodeComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (model.EpisodeComment, error)); ok {
		return rf(ctx, commentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) model.EpisodeComment); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Get(0).(model.EpisodeComment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeRepo_GetComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComment'
type EpisodeRepo_GetComment_Call struct {
	*mock.Call
}

// GetComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uint32
func (_e *EpisodeRepo_Expecter) GetComment(ctx interface{}, commentID interface{}) *EpisodeRepo_GetComment_Call {
	return &EpisodeRepo_GetComment_Call{Call: _e.mock.On("GetComment", ctx, commentID)}
}

func (_c *EpisodeRepo_GetComment_Call) Run(run func(ctx context.Context, commentID uint32)) *EpisodeRepo_GetComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *EpisodeRepo_GetComment_Call) Return(_a0 model.EpisodeComment, _a1 error) *EpisodeRepo_GetComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EpisodeRepo_GetComment_Call) RunAndReturn(run func(context.Context, uint32) (model.EpisodeComment, error)) *EpisodeRepo_GetComment_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, subjectID, filter, limit, offset
func (_m *EpisodeRepo) List(ctx context.Context, subjectID uint32, filter episode.Filter, limit int, offset int) ([]episode.Episode, error) {
	ret := _m.Called(ctx, subjectID, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []episode.Episode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, episode.Filter, int, int) ([]episode.Episode, error)); ok {
		return rf(ctx, subjectID, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, episode.Filter, int, int) []episode.Episode); ok {
		r0 = rf(ctx, subjectID, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]episode.Episode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, episode.Filter, int, int) error); ok {
		r1 = rf(ctx, subjectID, filter, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EpisodeRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID uint32
//   - filter episode.Filter
//   - limit int
//   - offset int
func (_e *EpisodeRepo_Expecter) List(ctx interface{}, subjectID interface{}, filter interface{}, limit interface{}, offset interface{}) *EpisodeRepo_List_Call {
	return &EpisodeRepo_List_Call{Call: _e.mock.On("List", ctx, subjectID, filter, limit, offset)}
}

func (_c *EpisodeRepo_List_Call) Run(run func(ctx context.Context, subjectID uint32, filter episode.Filter, limit int, offset int)) *EpisodeRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(episode.Filter), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *EpisodeRepo_List_Call) Return(_a0 []episode.Episode, _a1 error) *EpisodeRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EpisodeRepo_List_Call) RunAndReturn(run func(context.Context, uint32, episode.Filter, int, int) ([]episode.Episode, error)) *EpisodeRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// WithQuery provides a mock function with given fields: _a0
func (_m *EpisodeRepo) WithQuery(_a0 *query.Query) episode.Repo {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WithQuery")
	}

	var r0 episode.Repo
	if rf, ok := ret.Get(0).(func(*query.Query) episode.Repo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(episode.Repo)
		}
	}

	return r0
}

// EpisodeRepo_WithQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithQuery'
type EpisodeRepo_WithQuery_Call struct {
	*mock.Call
}

// WithQuery is a helper method to define mock.On call
//   - _a0 *query.Query
func (_e *EpisodeRepo_Expecter) WithQuery(_a0 interface{}) *EpisodeRepo_WithQuery_Call {
	return &EpisodeRepo_WithQuery_Call{Call: _e.mock.On("WithQuery", _a0)}
}

func (_c *EpisodeRepo_WithQuery_Call) Run(run func(_a0 *query.Query)) *EpisodeRepo_WithQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*query.Query))
	})
	return _c
}

func (_c *EpisodeRepo_WithQuery_Call) Return(_a0 episode.Repo) *EpisodeRepo_WithQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EpisodeRepo_WithQuery_Call) RunAndReturn(run func(*query.Query) episode.Repo) *EpisodeRepo_WithQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewEpisodeRepo creates a new instance of EpisodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEpisodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EpisodeRepo {
	mock := &EpisodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
