// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/bangumi/server/internal/model"
)

// TimeLineRepo is an autogenerated mock type for the TimeLineRepo type
type TimeLineRepo struct {
	mock.Mock
}

type TimeLineRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeLineRepo) EXPECT() *TimeLineRepo_Expecter {
	return &TimeLineRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TimeLineRepo) GetByID(ctx context.Context, id model.TimeLineID) (model.TimeLine, error) {
	ret := _m.Called(ctx, id)

	var r0 model.TimeLine
	if rf, ok := ret.Get(0).(func(context.Context, model.TimeLineID) model.TimeLine); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.TimeLine)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.TimeLineID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimeLineRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TimeLineRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id model.TimeLineID
func (_e *TimeLineRepo_Expecter) GetByID(ctx interface{}, id interface{}) *TimeLineRepo_GetByID_Call {
	return &TimeLineRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TimeLineRepo_GetByID_Call) Run(run func(ctx context.Context, id model.TimeLineID)) *TimeLineRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TimeLineID))
	})
	return _c
}

func (_c *TimeLineRepo_GetByID_Call) Return(_a0 model.TimeLine, _a1 error) *TimeLineRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type NewTimeLineRepoT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTimeLineRepo creates a new instance of TimeLineRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTimeLineRepo(t NewTimeLineRepoT) *TimeLineRepo {
	mock := &TimeLineRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
