// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bangumi/server/internal/domain"
	mock "github.com/stretchr/testify/mock"

	model "github.com/bangumi/server/internal/model"
)

// TopicRepo is an autogenerated mock type for the TopicRepo type
type TopicRepo struct {
	mock.Mock
}

type TopicRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TopicRepo) EXPECT() *TopicRepo_Expecter {
	return &TopicRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, topicType, id, limit, offset
func (_m *TopicRepo) Get(ctx context.Context, topicType domain.TopicType, id uint32, limit int, offset int) (model.Topic, error) {
	ret := _m.Called(ctx, topicType, id, limit, offset)

	var r0 model.Topic
	if rf, ok := ret.Get(0).(func(context.Context, domain.TopicType, uint32, int, int) model.Topic); ok {
		r0 = rf(ctx, topicType, id, limit, offset)
	} else {
		r0 = ret.Get(0).(model.Topic)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.TopicType, uint32, int, int) error); ok {
		r1 = rf(ctx, topicType, id, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopicRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TopicRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - topicType domain.TopicType
//  - id uint32
//  - limit int
//  - offset int
func (_e *TopicRepo_Expecter) Get(ctx interface{}, topicType interface{}, id interface{}, limit interface{}, offset interface{}) *TopicRepo_Get_Call {
	return &TopicRepo_Get_Call{Call: _e.mock.On("Get", ctx, topicType, id, limit, offset)}
}

func (_c *TopicRepo_Get_Call) Run(run func(ctx context.Context, topicType domain.TopicType, id uint32, limit int, offset int)) *TopicRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TopicType), args[2].(uint32), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *TopicRepo_Get_Call) Return(_a0 model.Topic, _a1 error) *TopicRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListTopics provides a mock function with given fields: ctx, topicType, id, limit, offset
func (_m *TopicRepo) ListTopics(ctx context.Context, topicType domain.TopicType, id uint32, limit int, offset int) (model.Topics, error) {
	ret := _m.Called(ctx, topicType, id, limit, offset)

	var r0 model.Topics
	if rf, ok := ret.Get(0).(func(context.Context, domain.TopicType, uint32, int, int) model.Topics); ok {
		r0 = rf(ctx, topicType, id, limit, offset)
	} else {
		r0 = ret.Get(0).(model.Topics)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.TopicType, uint32, int, int) error); ok {
		r1 = rf(ctx, topicType, id, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopicRepo_ListTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopics'
type TopicRepo_ListTopics_Call struct {
	*mock.Call
}

// ListTopics is a helper method to define mock.On call
//  - ctx context.Context
//  - topicType domain.TopicType
//  - id uint32
//  - limit int
//  - offset int
func (_e *TopicRepo_Expecter) ListTopics(ctx interface{}, topicType interface{}, id interface{}, limit interface{}, offset interface{}) *TopicRepo_ListTopics_Call {
	return &TopicRepo_ListTopics_Call{Call: _e.mock.On("ListTopics", ctx, topicType, id, limit, offset)}
}

func (_c *TopicRepo_ListTopics_Call) Run(run func(ctx context.Context, topicType domain.TopicType, id uint32, limit int, offset int)) *TopicRepo_ListTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TopicType), args[2].(uint32), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *TopicRepo_ListTopics_Call) Return(_a0 model.Topics, _a1 error) *TopicRepo_ListTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type NewTopicRepoT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTopicRepo creates a new instance of TopicRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTopicRepo(t NewTopicRepoT) *TopicRepo {
	mock := &TopicRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
