// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/bangumi/server/internal/model"
	mock "github.com/stretchr/testify/mock"

	user "github.com/bangumi/server/internal/user"
)

// UserRepo is an autogenerated mock type for the Repo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// CheckIsFriendToOthers provides a mock function with given fields: ctx, selfID, otherIDs
func (_m *UserRepo) CheckIsFriendToOthers(ctx context.Context, selfID model.UserID, otherIDs ...model.UserID) (bool, error) {
	_va := make([]interface{}, len(otherIDs))
	for _i := range otherIDs {
		_va[_i] = otherIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, selfID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, model.UserID, ...model.UserID) bool); ok {
		r0 = rf(ctx, selfID, otherIDs...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UserID, ...model.UserID) error); ok {
		r1 = rf(ctx, selfID, otherIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_CheckIsFriendToOthers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIsFriendToOthers'
type UserRepo_CheckIsFriendToOthers_Call struct {
	*mock.Call
}

// CheckIsFriendToOthers is a helper method to define mock.On call
//   - ctx context.Context
//   - selfID model.UserID
//   - otherIDs ...model.UserID
func (_e *UserRepo_Expecter) CheckIsFriendToOthers(ctx interface{}, selfID interface{}, otherIDs ...interface{}) *UserRepo_CheckIsFriendToOthers_Call {
	return &UserRepo_CheckIsFriendToOthers_Call{Call: _e.mock.On("CheckIsFriendToOthers",
		append([]interface{}{ctx, selfID}, otherIDs...)...)}
}

func (_c *UserRepo_CheckIsFriendToOthers_Call) Run(run func(ctx context.Context, selfID model.UserID, otherIDs ...model.UserID)) *UserRepo_CheckIsFriendToOthers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.UserID, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(model.UserID)
			}
		}
		run(args[0].(context.Context), args[1].(model.UserID), variadicArgs...)
	})
	return _c
}

func (_c *UserRepo_CheckIsFriendToOthers_Call) Return(_a0 bool, _a1 error) *UserRepo_CheckIsFriendToOthers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *UserRepo) GetByID(ctx context.Context, userID model.UserID) (user.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(context.Context, model.UserID) user.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *UserRepo_Expecter) GetByID(ctx interface{}, userID interface{}) *UserRepo_GetByID_Call {
	return &UserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *UserRepo_GetByID_Call) Run(run func(ctx context.Context, userID model.UserID)) *UserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserID))
	})
	return _c
}

func (_c *UserRepo_GetByID_Call) Return(_a0 user.User, _a1 error) *UserRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *UserRepo) GetByIDs(ctx context.Context, ids []model.UserID) (map[model.UserID]user.User, error) {
	ret := _m.Called(ctx, ids)

	var r0 map[model.UserID]user.User
	if rf, ok := ret.Get(0).(func(context.Context, []model.UserID) map[model.UserID]user.User); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.UserID]user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []model.UserID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type UserRepo_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []model.UserID
func (_e *UserRepo_Expecter) GetByIDs(ctx interface{}, ids interface{}) *UserRepo_GetByIDs_Call {
	return &UserRepo_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *UserRepo_GetByIDs_Call) Run(run func(ctx context.Context, ids []model.UserID)) *UserRepo_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.UserID))
	})
	return _c
}

func (_c *UserRepo_GetByIDs_Call) Return(_a0 map[model.UserID]user.User, _a1 error) *UserRepo_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByName provides a mock function with given fields: ctx, username
func (_m *UserRepo) GetByName(ctx context.Context, username string) (user.User, error) {
	ret := _m.Called(ctx, username)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type UserRepo_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepo_Expecter) GetByName(ctx interface{}, username interface{}) *UserRepo_GetByName_Call {
	return &UserRepo_GetByName_Call{Call: _e.mock.On("GetByName", ctx, username)}
}

func (_c *UserRepo_GetByName_Call) Run(run func(ctx context.Context, username string)) *UserRepo_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepo_GetByName_Call) Return(_a0 user.User, _a1 error) *UserRepo_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetFieldsByIDs provides a mock function with given fields: ctx, ids
func (_m *UserRepo) GetFieldsByIDs(ctx context.Context, ids []model.UserID) (map[model.UserID]user.Fields, error) {
	ret := _m.Called(ctx, ids)

	var r0 map[model.UserID]user.Fields
	if rf, ok := ret.Get(0).(func(context.Context, []model.UserID) map[model.UserID]user.Fields); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.UserID]user.Fields)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []model.UserID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetFieldsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFieldsByIDs'
type UserRepo_GetFieldsByIDs_Call struct {
	*mock.Call
}

// GetFieldsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []model.UserID
func (_e *UserRepo_Expecter) GetFieldsByIDs(ctx interface{}, ids interface{}) *UserRepo_GetFieldsByIDs_Call {
	return &UserRepo_GetFieldsByIDs_Call{Call: _e.mock.On("GetFieldsByIDs", ctx, ids)}
}

func (_c *UserRepo_GetFieldsByIDs_Call) Run(run func(ctx context.Context, ids []model.UserID)) *UserRepo_GetFieldsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.UserID))
	})
	return _c
}

func (_c *UserRepo_GetFieldsByIDs_Call) Return(_a0 map[model.UserID]user.Fields, _a1 error) *UserRepo_GetFieldsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetFriends provides a mock function with given fields: ctx, userID
func (_m *UserRepo) GetFriends(ctx context.Context, userID model.UserID) (map[model.UserID]user.FriendItem, error) {
	ret := _m.Called(ctx, userID)

	var r0 map[model.UserID]user.FriendItem
	if rf, ok := ret.Get(0).(func(context.Context, model.UserID) map[model.UserID]user.FriendItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.UserID]user.FriendItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriends'
type UserRepo_GetFriends_Call struct {
	*mock.Call
}

// GetFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *UserRepo_Expecter) GetFriends(ctx interface{}, userID interface{}) *UserRepo_GetFriends_Call {
	return &UserRepo_GetFriends_Call{Call: _e.mock.On("GetFriends", ctx, userID)}
}

func (_c *UserRepo_GetFriends_Call) Run(run func(ctx context.Context, userID model.UserID)) *UserRepo_GetFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserID))
	})
	return _c
}

func (_c *UserRepo_GetFriends_Call) Return(_a0 map[model.UserID]user.FriendItem, _a1 error) *UserRepo_GetFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
