all: false
dir: "./internal/mocks/"

force-file-write: true

log-level: info
pkgname: "mocks"
recursive: false
template: testify

filename: "{{.SrcPackageName | firstUpper}}{{.InterfaceName}}.go"
structname: "{{.SrcPackageName | firstUpper}}{{.InterfaceName}}"

packages:
  github.com/bangumi/server/web/session:
    interfaces:
      Repo:
