flowchart LR
  Users --> CloudFlare --> Old

  subgraph Old[old server]
    nginx
    nginx --> |旧主站|php[old php server];
  end


  nginx ---> |转发api.bgm.tv/v0/的请求| Nginx(nginx on new server);
  CloudFlare --> |next.bgm.tv 直接解析到新服务器|Nginx;

