flowchart TD
  Nginx(nginx on new server);

  Nginx -->|static new frontend files|FS[(file system)];

  Nginx -->|HTTP API Request|B;
  Nginx --> |HTTP Search request|meilisearch;

  C --> |增量更新数据|meilisearch;

  B --> mysql
  B --> |缓存|redis
  C --> |清除失效缓存|redis
  C --> |清除失效数据|mysql
  kafka --> C;


  subgraph B
    direction BT
    B1[chii web];
    B2[chii web];
    ...
  end

  subgraph C[canal]
    C1[chii canal];
  end

  meilisearch[(new search engine)];

  subgraph Components[database]
    direction BT
    redis[(redis 缓存)]
    mysql[(mysql)]
    kafka[(kafka)]
    mysql --> |binlog|kafka;
  end

