version: "3"

dotenv: [".env", ".envrc"]

includes:
  mock: "./etc/mock.task.yaml"

tasks:
  default:
    silent: true
    cmds:
      - task --list

  install:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/vektra/mockery/v2@latest
      - echo "install buf by yourself https://docs.buf.build/installation"

  build:
    desc: Build Web Server Binary
    sources:
      - ./**/*.go
      - go.mod
    generates:
      - ./dist/chii.exe
    cmds:
      - go build -trimpath -o dist/chii.exe main.go
    env:
      CGO_ENABLED: "0"

  lint:
    silent: true
    desc: Run 'golangci-lint'
    cmds:
      - golangci-lint run --fix

  test:
    desc: Run mocked tests, need nothing.
    cmds:
      - go test -timeout 3s -tags test {{.CLI_ARGS}} ./...
    env:
      CGO_ENABLED: "0"

  bench:
    desc: Run benchmark
    cmds:
      - go test -bench=. -benchmem ./pkg/wiki

  test-db:
    desc: Run mocked tests, and tests require mysql and redis. alias for `TEST_MYSQL=1 TEST_REDIS=1 task test`
    cmds:
      - go test -timeout 3s -tags test {{.CLI_ARGS}} ./...
    env:
      TEST_MYSQL: "1"
      TEST_REDIS: "1"

  test-http:
    desc: Run mocked tests, and tests require external HTTP resources, alias for `TEST_HTTP=1 task test`
    cmds:
      - go test -timeout 3s -tags test {{.CLI_ARGS}} ./...
    env:
      TEST_HTTP: "1"

  test-all:
    desc: Run all tests.
    cmds:
      - go test -timeout 10s -tags test ./...
    env:
      TEST_MYSQL: "1"
      TEST_REDIS: "1"
      TEST_HTTP: "1"

  coverage:
    desc: Run tests with coverage report, used in CI.
    cmds:
      - go test -timeout 10s -tags test -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./...
    env:
      TEST_MYSQL: "1"
      TEST_REDIS: "1"
      TEST_HTTP: "1"

  # generated files
  gen:
    desc: Generate all generated GO files
    cmds:
      - cmd: buf generate
      - task: gorm
      - task: mock
      - task: dal:comment

  dal:comment:
    sources:
      - ./cmd/gen/dal/**/*.go
    generates:
      - ./dal/dao/comment*.gen.go
    cmds:
      - go run ./cmd/gen/dal/comment.go

  mock:
    desc: Generate Mocks.
    deps:
      - mock:all

  gorm:
    desc: Run gorm-gen to generate go struct from mysql database.
    generates:
      - ./dal/query/gen.go
    sources:
      - ./cmd/gen/gorm/main.go
      - go.mod
    cmds:
      - go run ./cmd/gen/gorm/main.go

  clean:
    cmds:
      - rm -rf .task
      - rm -rf .bin
