// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNamePersonComment = "chii_prsn_comments"

// PersonComment mapped from table <chii_prsn_comments>
type PersonComment struct {
	ID          uint32 `gorm:"column:prsn_pst_id;type:mediumint(8) unsigned;primaryKey;autoIncrement:true" json:"prsn_pst_id"`
	MentionedID uint32 `gorm:"column:prsn_pst_mid;type:mediumint(8) unsigned;not null;index:cmt_prsn_id,priority:1" json:"prsn_pst_mid"` // 关联人物ID
	UID         uint32 `gorm:"column:prsn_pst_uid;type:mediumint(8) unsigned;not null;index:prsn_pst_uid,priority:1" json:"prsn_pst_uid"`
	Related     uint32 `gorm:"column:prsn_pst_related;type:mediumint(8) unsigned;not null;index:prsn_pst_related,priority:1" json:"prsn_pst_related"`
	CreatedAt   uint32 `gorm:"column:prsn_pst_dateline;type:int(10) unsigned;not null" json:"prsn_pst_dateline"`
	Content     string `gorm:"column:prsn_pst_content;type:mediumtext;not null" json:"prsn_pst_content"`
}

// TableName PersonComment's table name
func (*PersonComment) TableName() string {
	return TableNamePersonComment
}
