// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNamePersonComment = "chii_prsn_comments"

// PersonComment mapped from table <chii_prsn_comments>
type PersonComment struct {
	ID          uint32 `gorm:"column:prsn_pst_id;type:mediumint(8) unsigned;primaryKey;autoIncrement:true"`
	TopicID     uint32 `gorm:"column:prsn_pst_mid;type:mediumint(8) unsigned;not null"` // 关联人物ID
	UID         uint32 `gorm:"column:prsn_pst_uid;type:mediumint(8) unsigned;not null"`
	Related     uint32 `gorm:"column:prsn_pst_related;type:mediumint(8) unsigned;not null"`
	CreatedTime uint32 `gorm:"column:prsn_pst_dateline;type:int(10) unsigned;not null"`
	Content     string `gorm:"column:prsn_pst_content;type:mediumtext;not null"`
}

// TableName PersonComment's table name
func (*PersonComment) TableName() string {
	return TableNamePersonComment
}
