openapi: 3.0.2
info:
  title: "Bangumi Private API"
  version: ""
  description: "`next.bgm.tv` 域名不支持跨域，"
servers:
  - url: https://next.bgm.tv
    description: Production server

x-parameters:
  default_query_limit: &default_query_limit
    required: false
    schema:
      title: Limit
      maximum: 50
      minimum: 1
      type: integer
      default: 30
    name: limit
    description: 分页参数
    in: query

  default_query_offset: &default_query_offset
    required: false
    schema:
      title: Offset
      minimum: 0
      type: integer
      default: 0
    description: 分页参数
    name: offset
    in: query

tags:
  - name: Auth

paths:
  "/p/login":
    post:
      tags:
        - Auth
      summary: 登录
      operationId: login
      description: |
        `h-captcha-response` 是 [hCaptcha 的验证码](https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage)

        site key 是 `4874acee-9c6e-4e47-99ad-e2ea1606961f`
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - h-captcha-response
              properties:
                email:
                  type: string
                password:
                  type: string
                h-captcha-response:
                  type: string
      responses:
        "200":
          description: "账号密码正确，设置 Cookies"
          headers:
            Set-Cookie:
              description: 设置 cookies session
              schema:
                type: string
                example: sessionID=abcde12345; Path=/; HttpOnly
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"

        "400":
          description: 请求错误或者验证码错误
          content:
            application/json:
              example:
                "title": "Bad Request"
                "details":
                  - "Email为必填字段"
                  - "Password为必填字段"
                  - "HCaptchaResponse为必填字段"
                "description": "can't validate request body"
              schema:
                title: ErrorDetail
                required:
                  - title
                  - description
                  - detail
                type: object
                properties:
                  title:
                    title: Title
                    type: string
                  description:
                    title: Description
                    type: string
                  detail:
                    title: Detail
                    type: array
                    items:
                      type: string

        "401":
          description: 账号或密码错误
          content:
            application/json:
              schema:
                title: ErrorDetail
                required:
                  - title
                  - description
                  - detail
                type: object
                properties:
                  title:
                    title: Title
                    type: string
                  description:
                    title: Description
                    type: string
                  detail:
                    title: Detail
                    type: object
                    properties:
                      "remain":
                        type: integer
                        description: 剩余可用登录次数。

        "422":
          description: "无法以 JSON 格式解析请求"

        "502":
          description: hCaptcha HTTP 请求失败

  "/p/logout":
    post:
      tags:
        - Auth
      summary: 登出
      operationId: logout
      security:
        - CookiesSession: []
      responses:
        "204":
          description: "正常登出"

        "401":
          description: 用户未登录或者 session 已失效

  "/p/me":
    get:
      tags:
        - Auth
      summary: 获取当前用户
      operationId: getCurrentUser
      security:
        - CookiesSession: []
      responses:
        "200":
          description: "返回当前用户"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: 用户未登录或者 session 已失效

  "/p/groups/{name}":
    get:
      tags:
        - 小组
      summary: 获取小组首页信息
      operationId: getGroupProfileByName
      parameters:
        - name: name
          in: path
          schema:
            type: string
          description: "小组名，类似于 `https://bgm.tv/groups/boring` 的 `boring`"
          required: true
      responses:
        "200":
          description: "返回当前用户"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        "404":
          description: 小组不存在

  "/p/groups/{name}/members":
    get:
      tags:
        - 小组
      summary: 获取小组成员信息
      operationId: listGroupMembersByName
      parameters:
        - name: name
          in: path
          schema:
            type: string
          description: "小组名，类似于 `https://bgm.tv/groups/boring` 的 `boring`"
          required: true
        - name: type
          in: query
          schema:
            type: string
            default: "all"
            enum:
              - mod
              - normal
              - all
          description: 成员类型，默认为 `all`
          required: true
        - *default_query_limit
        - *default_query_offset
      responses:
        "200":
          description: "列出用户"
          content:
            application/json:
              schema:
                title: Paged[GroupMember]
                allOf:
                  - $ref: "#/components/schemas/Paged"
                  - type: object
                    properties:
                      data:
                        title: Data
                        type: array
                        items:
                          "$ref": "#/components/schemas/GroupMember"

        "404":
          description: 小组不存在

components:
  schemas:
    User:
      $ref: "./components/user.yaml"
    Group:
      $ref: "./components/private/group.yaml"
    Avatar:
      $ref: "./components/avatar.yaml"
    ErrorDetail:
      $ref: "./components/error_detail.yaml"
    Paged:
      type: object
      properties:
        total:
          title: Total
          type: integer
        limit:
          title: Limit
          type: integer
        offset:
          title: Offset
          type: integer
    GroupMember:
      type: array
      items:
        "$ref": "./components/private/group_member.yaml"
  securitySchemes:
    CookiesSession:
      name: sessionID
      type: apiKey
      in: cookie
