// Code generated by "stringer -type CollectionType -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CollectionWish-1]
	_ = x[CollectionDone-2]
	_ = x[CollectionDoing-3]
	_ = x[CollectionOnHold-4]
	_ = x[CollectionDropped-5]
}

const _CollectionType_name = "想看看过在看搁置抛弃"

var _CollectionType_index = [...]uint8{0, 6, 12, 18, 24, 30}

func (i CollectionType) String() string {
	i -= 1
	if i >= CollectionType(len(_CollectionType_index)-1) {
		return "CollectionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CollectionType_name[_CollectionType_index[i]:_CollectionType_index[i+1]]
}
