// Code generated by "stringer -output ./internal/model/episode_collection_type_string.gen.go -type EpisodeCollectionType -linecomment ./internal/model/episode_collection_type.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EpisodeCollectionTypeAll-0]
	_ = x[EpisodeCollectionTypeWish-1]
	_ = x[EpisodeCollectionTypeDone-2]
	_ = x[EpisodeCollectionTypeDropped-3]
}

const _EpisodeCollectionType_name = "全部想看看过抛弃"

var _EpisodeCollectionType_index = [...]uint8{0, 6, 12, 18, 24}

func (i EpisodeCollectionType) String() string {
	if i >= EpisodeCollectionType(len(_EpisodeCollectionType_index)-1) {
		return "EpisodeCollectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EpisodeCollectionType_name[_EpisodeCollectionType_index[i]:_EpisodeCollectionType_index[i+1]]
}
