// Code generated by ./internal/cmd/gen/null/main.go. DO NOT EDIT.

// SPDX-License-Identifier: AGPL-3.0-only
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>

package null

import (
	"github.com/goccy/go-json"
)

var _ json.Unmarshaler = (*Float32)(nil)

// Float32 is a nullable type.
type Float32 struct {
	Value float32
	Set   bool // if json object has this field
	Null  bool // if json field's value is `null`
}

// NewFloat32 creates a new float32.
func NewFloat32(t float32) Float32 {
	return Float32{
		Null:  false,
		Value: t,
		Set:   true,
	}
}

func (t Float32) HasValue() bool {
	return t.Set && !t.Null
}

func (t Float32) Ptr() *float32 {
	if t.Set && !t.Null {
		return &t.Value
	}

	return nil
}

// Default return default value its value is Null or not Set.
func (t Float32) Default(v float32) float32 {
	if t.Set && !t.Null {
		return t.Value
	}

	return v
}

func (t Float32) Interface() any {
	if t.HasValue() {
		return t.Value
	}

	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (t *Float32) UnmarshalJSON(data []byte) error {
	t.Set = true

	if string(data) == "null" {
		t.Null = true
		return nil
	}

	if err := json.UnmarshalNoEscape(data, &t.Value); err != nil {
		return err //nolint:wrapcheck
	}

	return nil
}
