// Code generated by ./internal/cmd/gen/null/main.go. DO NOT EDIT.

// SPDX-License-Identifier: AGPL-3.0-only
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>

package null

import (
	"github.com/goccy/go-json"
)

var _ json.Unmarshaler = (*Uint64)(nil)

// Uint64 is a nullable type.
type Uint64 struct {
	Value uint64
	Set   bool // if json object has this field
	Null  bool // if json field's value is `null`
}

// NewUint64 creates a new uint64.
func NewUint64(t uint64) Uint64 {
	return Uint64{
		Null:  false,
		Value: t,
		Set:   true,
	}
}

func (t Uint64) HasValue() bool {
	return t.Set && !t.Null
}

func (t Uint64) Ptr() *uint64 {
	if t.Set && !t.Null {
		return &t.Value
	}

	return nil
}

// Default return default value its value is Null or not Set.
func (t Uint64) Default(v uint64) uint64 {
	if t.Set && !t.Null {
		return t.Value
	}

	return v
}

func (t Uint64) Interface() any {
	if t.HasValue() {
		return t.Value
	}

	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (t *Uint64) UnmarshalJSON(data []byte) error {
	t.Set = true

	if string(data) == "null" {
		t.Null = true
		return nil
	}

	if err := json.UnmarshalNoEscape(data, &t.Value); err != nil {
		return err //nolint:wrapcheck
	}

	return nil
}
