// Code generated by "stringer -output ./internal/domain/collection_type_string.gen.go -type CollectionType -linecomment ./internal/domain/collection_type.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CollectionTypeAll-0]
	_ = x[CollectionTypeWish-1]
	_ = x[CollectionTypeDone-2]
	_ = x[CollectionTypeDoing-3]
	_ = x[CollectionTypeOnHold-4]
	_ = x[CollectionTypeDropped-5]
}

const _CollectionType_name = "全部想看看过在看搁置抛弃"

var _CollectionType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36}

func (i CollectionType) String() string {
	if i >= CollectionType(len(_CollectionType_index)-1) {
		return "CollectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CollectionType_name[_CollectionType_index[i]:_CollectionType_index[i+1]]
}
