// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNamePersonCollect = "chii_person_collects"

// PersonCollect 人物收藏
type PersonCollect struct {
	ID          uint32 `gorm:"column:prsn_clt_id;type:mediumint(8) unsigned;primaryKey;autoIncrement:true" json:""`
	Category    string `gorm:"column:prsn_clt_cat;type:enum('prsn','crt');not null" json:""`
	TargetID    uint32 `gorm:"column:prsn_clt_mid;type:mediumint(8) unsigned;not null" json:""`
	UserID      uint32 `gorm:"column:prsn_clt_uid;type:mediumint(8) unsigned;not null" json:""`
	CreatedTime uint32 `gorm:"column:prsn_clt_dateline;type:int(10) unsigned;not null" json:""`
}

// TableName PersonCollect's table name
func (*PersonCollect) TableName() string {
	return TableNamePersonCollect
}
