// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameCharacterSubjects = "chii_crt_subject_index"

// CharacterSubjects mapped from table <chii_crt_subject_index>
type CharacterSubjects struct {
	CharacterID   uint32    `gorm:"column:crt_id;type:mediumint(9) unsigned;primaryKey"`
	SubjectID     uint32    `gorm:"column:subject_id;type:mediumint(9) unsigned;primaryKey"`
	SubjectTypeID uint8     `gorm:"column:subject_type_id;type:tinyint(4) unsigned;not null"`
	CrtType       uint8     `gorm:"column:crt_type;type:tinyint(4) unsigned;not null;comment:主角，配角"`    // 主角，配角
	CtrAppearEps  string    `gorm:"column:ctr_appear_eps;type:mediumtext;not null;comment:可选，角色出场的的章节"` // 可选，角色出场的的章节
	CrtOrder      uint8     `gorm:"column:crt_order;type:tinyint(3) unsigned;not null"`
	Character     Character `gorm:"foreignKey:crt_id;references:crt_id" json:"character"`
	Subject       Subject   `gorm:"foreignKey:subject_id;references:subject_id" json:"subject"`
}

// TableName CharacterSubjects's table name
func (*CharacterSubjects) TableName() string {
	return TableNameCharacterSubjects
}
