// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"github.com/bangumi/server/internal/model"
)

const TableNamePrivateMessage = "chii_pms"

// PrivateMessage mapped from table <chii_pms>
type PrivateMessage struct {
	ID                model.PrivateMessageID `gorm:"column:msg_id;type:int(10) unsigned;primaryKey;autoIncrement:true"`
	SenderID          model.UserID           `gorm:"column:msg_sid;type:mediumint(8) unsigned;not null"`
	ReceiverID        model.UserID           `gorm:"column:msg_rid;type:mediumint(8) unsigned;not null"`
	Folder            string                 `gorm:"column:msg_folder;type:enum('inbox','outbox');not null;default:inbox"`
	New               bool                   `gorm:"column:msg_new;type:tinyint(1);not null"`
	Title             string                 `gorm:"column:msg_title;type:varchar(75);not null"`
	CreatedTime       uint32                 `gorm:"column:msg_dateline;type:int(10) unsigned;not null"`
	Content           string                 `gorm:"column:msg_message;type:text;not null"`
	MainMessageID     model.PrivateMessageID `gorm:"column:msg_related_main;type:int(10) unsigned;not null"`
	RelatedMessageID  model.PrivateMessageID `gorm:"column:msg_related;type:int(10) unsigned;not null"`
	DeletedBySender   bool                   `gorm:"column:msg_sdeleted;type:tinyint(1) unsigned;not null"`
	DeletedByReceiver bool                   `gorm:"column:msg_rdeleted;type:tinyint(1) unsigned;not null"`
}

// TableName PrivateMessage's table name
func (*PrivateMessage) TableName() string {
	return TableNamePrivateMessage
}
