name: release-cmd-archive

on:
  push:
    tags:
      - "v*.*.*"
env:
  USER: "bangumi"
  IMAGE: "chii-cmd-archive"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.17.8"

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: go build ./internal/cmd/archive -o dist/archive.exe

      - name: docker build
        run: docker build -f etc/archive.Dockerfile -t ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest .

      - name: docker login
        run: echo $DOCKER_TOKEN | docker login ghcr.io -u ${{ env.USER }} --password-stdin
        env:
          DOCKER_TOKEN: ${{ github.token }}

      - name: docker push
        run: |
          docker push ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest
          docker tag ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest "ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:$TAG"
          docker push "ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:$TAG"
