name: Security Vulnerability Check

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
      - ".github/workflows/security.yaml"
  schedule:
    - cron: "15 3 * * 4"

jobs:
  vulnerability-scan:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          submodules: true

      - uses: trim21/actions/setup-go@master
        with:
          cache-namespace: sec

      - run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - run: govulncheck ./...

      - name: Upsert vulncheck issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW: ${{ github.workflow }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
          SERVER_URL: ${{ github.server_url }}
          REPOSITORY: ${{ github.repository }}
        with:
          filename: .github/vulncheck-issue-template.md
          update_existing: true
          search_existing: all
